### PR TITLE
MVP

### PR DESCRIPTION
**Pull request by kkapsner**
@spodermenpls created a M(inimal)V(iable)P(roduct). I used very little from the original addon (I even recreated the icon to have an svg...).

Please test the functionality.

### CODE REVIEW

**Comment by theAlinP** [comment]
I can't test it right now. Maybe @spodermenpls or @jobisoft can do it.

**Comment by spodermenpls** [comment]
@kkapsner Thank you very much for your swift work. I've just tested it out, the converting-while-writing works well, "Auf Auswahl anwenden" though not so much. When I select a text with "words in quotations" and click the button, nothing happens.

**Comment by kkapsner** [comment]
Please retry.

**Comment by spodermenpls** [comment]
@kkapsner No movement, still. Does "apply on selection" work on your end? - I am using TB 78.4.1, there was an update yesterday.

**Comment by kkapsner** [comment]
Yes it did, but I was testing on TB 84.0a1... 78.4.0 works as well - let's do the update... works also.

**Comment by spodermenpls** [comment]
@kkapsner Am I doing it wrong, or what's hindering it on my end? - I type in _"Hallo"_, select it with the cursor, click on the "Smart Quotes" badge, and click on the "... Anwenden" button, while "SmartQuote active" is ticked and (in this case) 'Deutsch' is selected. 
I also use the add-on "ReplyWithHeader", that might potentially interfere, while being deactivated the "converting-after-writing" still doesn't work, though.

I also noticed that after hitting "Enter" to start a new line, "Smart Quotes" always uses upper-case "quotation marks", even if it's set to be German. Quotes after that, on the same line, use the lower-case quotes then, though. Example:

```
„Hallo“ „Hallo“ „Hallo“

“Hallo“ „Hallo“ „Hallo“

“Hallo“ „Hallo“ „Hallo“
```

**Comment by kkapsner** [comment]
@spodermenpls Your actions seem correct . They work for me:
Peek 2020-11-08 13-24

The line break thing was a bigger thing... they are handled very weird in Thunderbird (and Firefox). Please test again.

**Comment by theAlinP** [comment]
I tested the updated build and it works correctly now.

**Comment by spodermenpls** [comment]
@kkapsner Okay, I've been able to tighten the noose around the problem a bit, converting an English quote into a German quote works, however turning a German quote into an English quote does not.

**Comment by theAlinP** [comment]
@spodermenpls If you're talking about converting one set of "smart" quotes into another, you're right.

**Comment by kkapsner** [comment]
What do you exactly mean by "English quote"? Do you mean `"Hallo"` or `“Hallo”`?

**Comment by spodermenpls** [comment]
I observed this with the first style, so the issue is more so the inability to change the quotation style after it's been done once before.

**Comment by kkapsner** [comment]
Yes, changing the style after the fact is not implemented.

**Pull request merged**
